name: 🐞 Bug Report
description: File a bug report
title: "[BUG] <short description>"
labels: ["kind/bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill this out!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: Tell us what you saw
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. `...`
        2. `...`
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Trion version
      placeholder: e.g. 1.0.0-preview.3
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell